### ISSUE TITLE
sort_finish_pending regression test gives a false positive easily

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#627]
The sort_finish_pending test case isn't very reliable, in the sense that it's not necessarily testing what it's supposed to test. The invocation of "gpfaultinjector" is inside an ignore-block, and if that invocation fails, the test passes just fine. This is what the output looks like when gpfaultinjector is not in PATH, and the test still passed:

```
drop table if exists _tmp_table;
NOTICE:  table "_tmp_table" does not exist, skipping
create table _tmp_table (i1 int, i2 int, i3 int, i4 int);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'i1' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
insert into _tmp_table select i, i % 100, i % 10000, i % 75 from generate_series(0,99999) i;
-- make sort to spill
set statement_mem="2MB";
set gp_enable_mk_sort=on;
set gp_cte_sharing=on;
--start_ignore
\! gpfaultinjector -f execsort_mksort_mergeruns -y reset --seg_dbid 2
sh: 1: gpfaultinjector: not found
-- set QueryFinishPending=true in sort mergeruns. This will stop sort and set result_tape to NULL
\! gpfaultinjector -f execsort_mksort_mergeruns -y finish_pending --seg_dbid 2
sh: 1: gpfaultinjector: not found
--end_ignore
-- return results although sort will be interrupted in one of the segments 
select DISTINCT S from (select row_number() over(partition by i1 order by i2) AS T, count(*) over (partition by i1) AS S from _tmp_table) AS TMP;
 s 

---
 1
(1 row)
```

**Comment by armenatzoglou** [comment]
Agree. I just opened a PR that solves this issue: https://github.com/greenplum-db/gpdb/pull/698

**Comment by armenatzoglou** [comment]
Fix has been pushed to master https://github.com/greenplum-db/gpdb/commit/d3edab914cb335d261e19a134fb3842e4c1cc373. Thanks a lot

**Comment by armenatzoglou** [comment]
The fix did not solve the problem completely and we had to revert it. The new issue is related to gp_primarymirror, which has an unexpected behavior. We will push back the code when we fix gp_primarymirror issue.

Me and @ashwinstar started working on gp_primarymirror issue.

**Comment by ivannovick** [comment]
@ashwinstar @hlinnaka @Eulerizeit can this be closed?

**Comment by ashwinstar** [comment]
@armenatzoglou please can you see if its still happening on latest master. I feel the commit 728119a4487bef351730c907b96c8ce47982b824 might have as side effect fixed this problem as well. If not please let me know.

**Comment by armenatzoglou** [comment]
The fix has been pushed to master: 554b878fdd4ff28100b4ffd37f91e82693540067. I and @hsyuan moved gpfaultinjector out of start/end ignore blocks, made gpfaultinjector less noisy, and modified the related icg tests accordingly.  

We close this issue.
